### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by tseemann** [CDCgov/SanitizeMe#1]
```
No description, website, or topics provided.
```

FIRST ISSUE!

**Comment by jiangweiyao** [comment]
Thanks for reporting the issue. Description should be added now.

**Comment by leebrian** [comment]
I think this is the first time someone whose handle I don't know has suggest an issue related to the CDC open practices, https://github.com/CDCgov/template/blob/master/open_practices.md

Thanks @tseemann for finding this, and thanks @jiangweiyao for adding a description. Please consider adding topics as well to help people find your project, especially when they are indexed up at code.gov.

**Comment by tseemann** [comment]
@leebrian excited to see this CDC policy for open source software!
