### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by tseemann** [CDCgov/SanitizeMe#2]
requires direct access to a linux computer or X11 forwarding.

Image description  <------ image not there

It uses Minimap2 to map to

**Comment by jiangweiyao** [comment]
Hi Torsten,

I changed the link for the image so it should be showing up now. I can see it from my computer. Please let me know if you still have problem seeing the image. Thank you so much for reporting the problem!

**Comment by jiangweiyao** [comment]
Should be fixed. Please let me know if it is not.
